package com.seekasia.emailsystem.constant;

public class CanditateConstant {
	public static final String USERNAME = "seekasiaemail@gmail.com";
	public static final String PASSWORD = "Seekasiaemail12";
	public static final String EMAIL_FROM_RECEIPIENT = "seekasiaemail@gmail.com";
	public final static String ACTIVE_EMAIL_SUBJECT = "Reminder email for the 'Tech Lead' position";
	public final static String ACTIVE_EMAIL_MESSAGE = "Please reply the message asap";
	public final static String BATCH_UPDATE_QUERY = "update Candidate set emailStatus= :status where emailStatus= :eStatus and recuriterEmailSendDate< :emailSendDate";
	public final static String SELECT_QUERY="from Candidate C where C.email= :email";
	public final static String CANDIDATE = "candidate";
	public final static String ADD_VIEW_FORM = "add-candidate-form";
	public final static String CANDIDATE_LOGIN_FORM = "candidate-login-form";
	public final static String CANDIDATE_LIST_FORM = "list-of-candidates";
	public final static String CANDIDATE_EDIT_FORM = "edit-candidate-form";
	public final static String MESSAGE =  "message";
	public final static String SUCCESS = "Success"; 
	public final static String UPDATE_SUCCESS_MSG = "Candidate record was updated successfully!!!";
	public final static String EMAIL_SUCCESS_MSG = "Email successfully sent it to the recipient!!!";
	public final static String DELETE_SUCCESS_MSG = "Candidate record was deleted successfully!!!";
	public final static String LOGIN_SUCCESS_MSG = "Login Success!!!";
	public final static String LOGIN_FAILED_MSG = "Login failed, Please checck your login ID!!!";
	public final static String HOME_MSG = "home";
	public final static String ACTIVE_STATUS = "Active";
	public final static String FAILED_STATUS = "Failed , Email already exists in the system. Please check it";
	public final static String FROM_CANDIDATE = "from Candidate";
	public final static String FROM_ACTIVE_CANDIDATE = "from Candidate where emailStatus = 'Active'";
	public final static String FROM_NON_RESPONSIVE_CANDIDATE = "from Candidate where emailStatus = 'Not Responsive'";
	public final static String EMAI_LBL = "email";
	public final static String STATUS_KEY = "status";
	public final static String E_STATUS_KEY = "eStatus";
	public final static String E_SEND_DATE_KEY ="emailSendDate";
	public final static String DISPATCHER = "dispatcher";
	public final static String PREFIX = "/WEB-INF/pages/";
	public final static String JSP_SUFFIX = ".jsp";
	public final static String ASSETS_LBL = "/assets/**";
	public final static String ASSETS_LABEL = "/assets/";
	public final static String NON_RESPONSIVE = "Non Responsive";
	public final static int UPDATE_4DAYS_FREQUENCY = 4;
	public final static int UPDATE_2DAYS_FREQUENCY = 2;
	public final static String INACTIVE = "Inactive";
	public final static String LOGIN_AUTH_FAILED ="Authentication failed";
	public final static String WRONG_EMAIL = "Wrong email address";
	public final static String GATEWAY = "smtp.gmail.com";
	public final static String GMAIL_PORT = "465";
	public final static String GMAIL_FACTORY = "javax.net.ssl.SSLSocketFactory";
	public final static String TRUE = "true";
	public final static String FALSE =  "false";
}
